name: IGNOU Scraper

on:
  schedule:
    - cron: '0 * * * *' # Har 1 ghante mein chalega
  workflow_dispatch: # Manual button ke liye

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run Scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python scraper.py
